---
title: "Readings"
---

*This page is mostly for personal use, to keep track of the books I read and want to read.*

*These are mostly books in italian by italian authors.*

## On the list
**L'Homme qui regardait passer les trains**, Georges Simenon, Folio, 1980 (*Gallimar, 1938*)

**L'adversaire**, Emmanuel Carrère, Folio, 2013 (*P.O.L., 2000*)  

**Limonov**, Emmanuel Carrère, Folio, 2013 (*P.O.L., 2011*)

**Il giorno del giudizio**, Salvatore Satta, Adelphi, 1990 (*CEDAM, 1977*)

**Mitocrazia** (Orig. *Mythocratie. Storytelling et imaginaire de gauche*), Yves Citton, Alegre, 2013. 

**Dialettica dell’illuminismo** (Orig. *Dialektik der Aufklärung. Philosophische Fragmente*),  Max Horkheimer, Theodor W. Adorno, Einaudi, 2010. 

## 2026
**L'età fragile**, Donatella Di Pietrantonio, Einaudi, 2023.

**Giù nella valle**, Paolo Cognetti, Einaudi, 2023.

## Past years

<details>
  <summary> 2025 </summary>
**Festa con casuario**, Leonardo San Pietro, Sellerio, 2025.<br />
**Una vita come tante** (Orig. *A Little Life*), Hanya Yanagihara, Sellerio, 2016.<br />
**Mensaleri**, Wu Ming 2, Einaudi, 2025.<br />
**La falce dei cieli**  (Orig. *The Lathe of Heaven*), Ursula K. Le Guin, Mondadori, 2025.<br />
**The Human Stain**, Philip Roth, Vintage, 2025 (*Houghton Mifflin, 2000*)<br />
**Lo sbilico**, Alcide Pierantozzi, Einaudi, Einaudi, 2025.<br />
**La felicità del lupo**, Paolo Cognetti, Einaudi, 2021.<br />
**Poveri a noi**, Elvio Carrieri, Ventanas, 2024.<br />
**Point Lenana**, Wu Ming 1 e Roberto Santachiara, Einaudi, 2016.<br />
**Una questione privata**, Beppe Fenoglio, Einaudi, 2022 (*Garzanti, 1963*)<br />
**Orso** (Orig. *Bear*), Marian Engel, La  Nuova Frontiera, 2024.<br />
**Incompletezza**, Deborah Gambetta, Ponte alle Grazie, 2024.<br />
**Sostiene Pereira**, Antonio Tabucchi, Feltrinelli, 2019 (*Feltrinelli, 1995*)<br />
**Portnoy** (Orig. *Portnoy's Complaint*), Philip Roth, Adelphi, 2025.<br />
**Abel**, Alessandro Baricco, Feltrinelli, 2023.<br />
**Il calcio del figlio**, Wu Ming 4, Alegre, 2025.<br />
**Lessico familiare**, Natalia Ginzburg, Einaudi, 2014 (*Einaudi, 1963*).<br />
**La breve stagione** (Orig. *Colchiques dans les prés*), Serge Quadruppani, Alegre, 2024.<br /> 
**La macchina del vento**, Wu Ming 1, Einaudi, 2019.<br />
**Stirpe e vergogna**, Michela Marzano, Rizzoli, 2021.<br />
**Gli uomini pesce**, Wu Ming 1, Einaudi, 2024.<br />
**25**, Bernardo Zannoni, Sellerio, 2023.<br />
**I miei stupidi intenti**, Bernardo Zannoni, Sellerio, 2021.<br />
**La luna e i falò**, Cesare Pavese, La Stampa, 2008 (*Einaudi, 1950*).<br />
**Cantalamappa. Tutte le storie**, Wu Ming, Electa Junior, 2024.<br />
**La vera storia della banda Hood**, Wu Ming 4, Bompiani, 2024.<br />
**La strangera**, Marta Aidala, Guanda, 2024.<br />
**Il ragazzo selvatico. Quaderno di montagna**, Paolo Cognetti, Terre di Mezzo, 2013.<br />
**Le venti giornate di Torino**, Giorgio de Maria, Frassinelli, 2017 (*Il formichiere, 1977*).
</details>